//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duil_App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duil_App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso Negado.
        /// </summary>
        public static string AcessoNegado {
            get {
                return ResourceManager.GetString("AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possui permissões para aceder a esta página..
        /// </summary>
        public static string AcessoNegadoText {
            get {
                return ResourceManager.GetString("AcessoNegadoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Fábrica.
        /// </summary>
        public static string adicionarFabrica {
            get {
                return ResourceManager.GetString("adicionarFabrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Fábrica.
        /// </summary>
        public static string adicionarFabricaViewTitle {
            get {
                return ResourceManager.GetString("adicionarFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPeca {
            get {
                return ResourceManager.GetString("AdicionarPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPecaemEncomendas {
            get {
                return ResourceManager.GetString("AdicionarPecaemEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPecaVT {
            get {
                return ResourceManager.GetString("AdicionarPecaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar restantes peças do Cliente.
        /// </summary>
        public static string AdicionarrestantespeçasdoCliente {
            get {
                return ResourceManager.GetString("AdicionarrestantespeçasdoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar cliente.
        /// </summary>
        public static string AdidionarCliente {
            get {
                return ResourceManager.GetString("AdidionarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar dados de Utilizador.
        /// </summary>
        public static string AlterarInfodeUtilizador {
            get {
                return ResourceManager.GetString("AlterarInfodeUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nossa história.
        /// </summary>
        public static string ANossaHistoria {
            get {
                return ResourceManager.GetString("ANossaHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Duil começou em 1972. Nasceu com o sonho de promover produtos e competências portuguesas no estrangeiro, com foco nos mercados escandinavos, mantendo a porta aberta para o resto do mundo..
        /// </summary>
        public static string ANossaHistoriaTexto {
            get {
                return ResourceManager.GetString("ANossaHistoriaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nossa missão.
        /// </summary>
        public static string ANossaMissao {
            get {
                return ResourceManager.GetString("ANossaMissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar ligações duradouras entre as nossas fábricas e os mercados internacionais..
        /// </summary>
        public static string ANossaMissaoTexto {
            get {
                return ResourceManager.GetString("ANossaMissaoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Fábrica.
        /// </summary>
        public static string ApagarFabricaViewTitle {
            get {
                return ResourceManager.GetString("ApagarFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Peça.
        /// </summary>
        public static string apagarPecasVT {
            get {
                return ResourceManager.GetString("apagarPecasVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo à plataforma da Duil!.
        /// </summary>
        public static string BemVindoADuil {
            get {
                return ResourceManager.GetString("BemVindoADuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao seu perfil,.
        /// </summary>
        public static string bemvindoperfil {
            get {
                return ResourceManager.GetString("bemvindoperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string Cancelada {
            get {
                return ResourceManager.GetString("Cancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja terminar a sessão?.
        /// </summary>
        public static string CertezaLogOut {
            get {
                return ResourceManager.GetString("CertezaLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar empresa cliente.
        /// </summary>
        public static string ClienteCreateTitle {
            get {
                return ResourceManager.GetString("ClienteCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Empresa Cliente.
        /// </summary>
        public static string ClienteCreateViewTitle {
            get {
                return ResourceManager.GetString("ClienteCreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente é obrigatório.
        /// </summary>
        public static string clienteeobrigatorio {
            get {
                return ResourceManager.GetString("clienteeobrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Cliente.
        /// </summary>
        public static string ClienteNome {
            get {
                return ResourceManager.GetString("ClienteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string ClienteRole {
            get {
                return ResourceManager.GetString("ClienteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string CodPostal {
            get {
                return ResourceManager.GetString("CodPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concretizada.
        /// </summary>
        public static string Concretizada {
            get {
                return ResourceManager.GetString("Concretizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Password.
        /// </summary>
        public static string ConfirmacaodePassword {
            get {
                return ResourceManager.GetString("ConfirmacaodePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmada.
        /// </summary>
        public static string Confirmada {
            get {
                return ResourceManager.GetString("Confirmada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Email.
        /// </summary>
        public static string ConfirmarEmail {
            get {
                return ResourceManager.GetString("ConfirmarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Terminar Sessão.
        /// </summary>
        public static string ConfirmarLogOut {
            get {
                return ResourceManager.GetString("ConfirmarLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar palavra-passe.
        /// </summary>
        public static string ConfirmarPasse {
            get {
                return ResourceManager.GetString("ConfirmarPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar registo.
        /// </summary>
        public static string ConfirmarRegisto {
            get {
                return ResourceManager.GetString("ConfirmarRegisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Email.
        /// </summary>
        public static string ConfirmationEmail {
            get {
                return ResourceManager.GetString("ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, confirme o seu endereço de email ao clicar no botão abaixo:.
        /// </summary>
        public static string ConfirmeEmailAo {
            get {
                return ResourceManager.GetString("ConfirmeEmailAo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Registo.
        /// </summary>
        public static string ConfirmRegist {
            get {
                return ResourceManager.GetString("ConfirmRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Nova Palavra-passe.
        /// </summary>
        public static string confnewPW {
            get {
                return ResourceManager.GetString("confnewPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta conta foi bloqueada. Por favor tente mais tarde..
        /// </summary>
        public static string Contabloquead {
            get {
                return ResourceManager.GetString("Contabloquead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua conta foi criada com sucesso! Por favor verifique o seu email para confirmar a sua conta..
        /// </summary>
        public static string ContaCriada {
            get {
                return ResourceManager.GetString("ContaCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Criar {
            get {
                return ResourceManager.GetString("Criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar encomenda.
        /// </summary>
        public static string CriarEncomenda {
            get {
                return ResourceManager.GetString("CriarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe Atual.
        /// </summary>
        public static string curPW {
            get {
                return ResourceManager.GetString("curPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string DadosPEssoais {
            get {
                return ResourceManager.GetString("DadosPEssoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        public static string Designacao {
            get {
                return ResourceManager.GetString("Designacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Fábrica.
        /// </summary>
        public static string DetalhesdaFabricaViewTitle {
            get {
                return ResourceManager.GetString("DetalhesdaFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de.
        /// </summary>
        public static string DetalhesDe {
            get {
                return ResourceManager.GetString("DetalhesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de.
        /// </summary>
        public static string detalhesDeAlgo {
            get {
                return ResourceManager.GetString("detalhesDeAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Utilizador.
        /// </summary>
        public static string DetalhesdoUtilizador {
            get {
                return ResourceManager.GetString("DetalhesdoUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Encomenda.
        /// </summary>
        public static string detalhesEncomendaViewTitle {
            get {
                return ResourceManager.GetString("detalhesEncomendaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da peça ref: .
        /// </summary>
        public static string DetalhesPeca {
            get {
                return ResourceManager.GetString("DetalhesPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhesTexto {
            get {
                return ResourceManager.GetString("detalhesTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinamarca.
        /// </summary>
        public static string Dinamarca {
            get {
                return ResourceManager.GetString("Dinamarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuição.
        /// </summary>
        public static string Dist {
            get {
                return ResourceManager.GetString("Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * é de preenchimento obrigatório.
        /// </summary>
        public static string eDePreenchimentoObrigatorio {
            get {
                return ResourceManager.GetString("eDePreenchimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro com o envio do Email..
        /// </summary>
        public static string EmailEnviadoErr {
            get {
                return ResourceManager.GetString("EmailEnviadoErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Enviado com sucesso..
        /// </summary>
        public static string EmailEnviadoSuc {
            get {
                return ResourceManager.GetString("EmailEnviadoSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nome@exemplo.com.
        /// </summary>
        public static string EmailExemplo {
            get {
                return ResourceManager.GetString("EmailExemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Transportadora.
        /// </summary>
        public static string EmpresaTrans {
            get {
                return ResourceManager.GetString("EmpresaTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomendas.
        /// </summary>
        public static string Encomendas {
            get {
                return ResourceManager.GetString("Encomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomendas Concretizadas.
        /// </summary>
        public static string EncomendasConcretizadas {
            get {
                return ResourceManager.GetString("EncomendasConcretizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomenda criada com sucesso!.
        /// </summary>
        public static string encomendaSuc {
            get {
                return ResourceManager.GetString("encomendaSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomenda.
        /// </summary>
        public static string EncomendaTexto {
            get {
                return ResourceManager.GetString("EncomendaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao alterar o número de telemóvel..
        /// </summary>
        public static string errotelm {
            get {
                return ResourceManager.GetString("errotelm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a password?.
        /// </summary>
        public static string esqueceu {
            get {
                return ResourceManager.GetString("esqueceu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a palavra-passe?.
        /// </summary>
        public static string EsqueceuPP {
            get {
                return ResourceManager.GetString("EsqueceuPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string EstadoCancelada {
            get {
                return ResourceManager.GetString("EstadoCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concretizada.
        /// </summary>
        public static string EstadoConcretizada {
            get {
                return ResourceManager.GetString("EstadoConcretizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmada.
        /// </summary>
        public static string EstadoConfirmada {
            get {
                return ResourceManager.GetString("EstadoConfirmada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado de .
        /// </summary>
        public static string EstadoDe {
            get {
                return ResourceManager.GetString("EstadoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string EstadoPendente {
            get {
                return ResourceManager.GetString("EstadoPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados Unidos da América.
        /// </summary>
        public static string EstadosUnidosdaAmerica {
            get {
                return ResourceManager.GetString("EstadosUnidosdaAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatísticas.
        /// </summary>
        public static string Estatisticas {
            get {
                return ResourceManager.GetString("Estatisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to este.
        /// </summary>
        public static string esteHelper {
            get {
                return ResourceManager.GetString("esteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábrica .
        /// </summary>
        public static string Fabrica {
            get {
                return ResourceManager.GetString("Fabrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fábrica é obrigatória.
        /// </summary>
        public static string fabricaeobrigatoria {
            get {
                return ResourceManager.GetString("fabricaeobrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da fábrica.
        /// </summary>
        public static string FabricaNome {
            get {
                return ResourceManager.GetString("FabricaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábricas.
        /// </summary>
        public static string Fabricas {
            get {
                return ResourceManager.GetString("Fabricas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatos permitidos: .jpg, .jpeg, .png, .gif, .webp.
        /// </summary>
        public static string FormatosImagemPermitidos {
            get {
                return ResourceManager.GetString("FormatosImagemPermitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to França.
        /// </summary>
        public static string Franca {
            get {
                return ResourceManager.GetString("Franca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levamos o melhor de Portugal ao mundo..
        /// </summary>
        public static string FraseDeImpacto {
            get {
                return ResourceManager.GetString("FraseDeImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        public static string FuncionarioRole {
            get {
                return ResourceManager.GetString("FuncionarioRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Alterações.
        /// </summary>
        public static string GuardarAlteracoes {
            get {
                return ResourceManager.GetString("GuardarAlteracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holanda.
        /// </summary>
        public static string Holanda {
            get {
                return ResourceManager.GetString("Holanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem atual.
        /// </summary>
        public static string ImagemAtual {
            get {
                return ResourceManager.GetString("ImagemAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem da Peça.
        /// </summary>
        public static string ImagemdoclientePeca {
            get {
                return ResourceManager.GetString("ImagemdoclientePeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem padrão.
        /// </summary>
        public static string ImagempadraoPeca {
            get {
                return ResourceManager.GetString("ImagempadraoPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string ImagemPeca {
            get {
                return ResourceManager.GetString("ImagemPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas Clientes.
        /// </summary>
        public static string IndexClientes {
            get {
                return ResourceManager.GetString("IndexClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglaterra.
        /// </summary>
        public static string Inglaterra {
            get {
                return ResourceManager.GetString("Inglaterra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sessão.
        /// </summary>
        public static string IniciarSessao {
            get {
                return ResourceManager.GetString("IniciarSessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o seu email..
        /// </summary>
        public static string Insiraemail {
            get {
                return ResourceManager.GetString("Insiraemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um utilizador com esse nome..
        /// </summary>
        public static string JaExiste {
            get {
                return ResourceManager.GetString("JaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Encomenda.
        /// </summary>
        public static string LastE {
            get {
                return ResourceManager.GetString("LastE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me?.
        /// </summary>
        public static string Lembrarme {
            get {
                return ResourceManager.GetString("Lembrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Encomenda.
        /// </summary>
        public static string modificarEncomendaViewTitle {
            get {
                return ResourceManager.GetString("modificarEncomendaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Fábrica.
        /// </summary>
        public static string ModificarFábricaVT {
            get {
                return ResourceManager.GetString("ModificarFábricaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Peça.
        /// </summary>
        public static string ModificarPecaVT {
            get {
                return ResourceManager.GetString("ModificarPecaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string modificarTexto {
            get {
                return ResourceManager.GetString("modificarTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Morada {
            get {
                return ResourceManager.GetString("Morada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada de carga.
        /// </summary>
        public static string MoradaCarga {
            get {
                return ResourceManager.GetString("MoradaCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada de descarga.
        /// </summary>
        public static string MoradaDescarga {
            get {
                return ResourceManager.GetString("MoradaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça Mais Encomendada.
        /// </summary>
        public static string moree {
            get {
                return ResourceManager.GetString("moree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mude a sua palavra-passe..
        /// </summary>
        public static string MudePW {
            get {
                return ResourceManager.GetString("MudePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string NavClientes {
            get {
                return ResourceManager.GetString("NavClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Encomenda.
        /// </summary>
        public static string NavCriarEncomenda {
            get {
                return ResourceManager.GetString("NavCriarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomendas.
        /// </summary>
        public static string NavEncomendas {
            get {
                return ResourceManager.GetString("NavEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábricas.
        /// </summary>
        public static string NavFabricas {
            get {
                return ResourceManager.GetString("NavFabricas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peças.
        /// </summary>
        public static string NavPecas {
            get {
                return ResourceManager.GetString("NavPecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo de Encomendas.
        /// </summary>
        public static string NavRegistoEncomendas {
            get {
                return ResourceManager.GetString("NavRegistoEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string NavUtilizadores {
            get {
                return ResourceManager.GetString("NavUtilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Palavra-passe.
        /// </summary>
        public static string newPW {
            get {
                return ResourceManager.GetString("newPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem encomendas para comparação..
        /// </summary>
        public static string NoEE {
            get {
                return ResourceManager.GetString("NoEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente.
        /// </summary>
        public static string NomeCliente {
            get {
                return ResourceManager.GetString("NomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente.
        /// </summary>
        public static string NomeDoCliente {
            get {
                return ResourceManager.GetString("NomeDoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova encomenda.
        /// </summary>
        public static string NovaEncomenda {
            get {
                return ResourceManager.GetString("NovaEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Peças Associadas.
        /// </summary>
        public static string NPecas {
            get {
                return ResourceManager.GetString("NPecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é de preenchimento obrigatório.
        /// </summary>
        public static string obrigatorio {
            get {
                return ResourceManager.GetString("obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se registar na nossa plataforma.
        /// </summary>
        public static string Obrugadoregisto {
            get {
                return ResourceManager.GetString("Obrugadoregisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá .
        /// </summary>
        public static string Ola {
            get {
                return ResourceManager.GetString("Ola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O que fazemos.
        /// </summary>
        public static string OQueFazemos {
            get {
                return ResourceManager.GetString("OQueFazemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promovemos produtos, apoiamos o desenvolvimento de novas ideias e acompanhamos todo o processo até ao envio..
        /// </summary>
        public static string OQueFazemosTexto {
            get {
                return ResourceManager.GetString("OQueFazemosTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de encomenda.
        /// </summary>
        public static string OrdemDeEncomenda {
            get {
                return ResourceManager.GetString("OrdemDeEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Inicial.
        /// </summary>
        public static string PaginaInicialViewTitle {
            get {
                return ResourceManager.GetString("PaginaInicialViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe.
        /// </summary>
        public static string Palavrapasse {
            get {
                return ResourceManager.GetString("Palavrapasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As palavras-passses não coincidem.
        /// </summary>
        public static string PasswordsNaoCoincidem {
            get {
                return ResourceManager.GetString("PasswordsNaoCoincidem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça.
        /// </summary>
        public static string Peca {
            get {
                return ResourceManager.GetString("Peca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peças.
        /// </summary>
        public static string Pecas {
            get {
                return ResourceManager.GetString("Pecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string Pendente {
            get {
                return ResourceManager.GetString("Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos/Referências/Sobre.
        /// </summary>
        public static string policy {
            get {
                return ResourceManager.GetString("policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um cliente para ver as peças.
        /// </summary>
        public static string PorfavorAdicioneClienteParaPecas {
            get {
                return ResourceManager.GetString("PorfavorAdicioneClienteParaPecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço total (€).
        /// </summary>
        public static string PrecoTotal {
            get {
                return ResourceManager.GetString("PrecoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço unitário.
        /// </summary>
        public static string PrecoUnit {
            get {
                return ResourceManager.GetString("PrecoUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira a sua password.
        /// </summary>
        public static string PVentrepw {
            get {
                return ResourceManager.GetString("PVentrepw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua palavra-passe foi alterada com sucesso.
        /// </summary>
        public static string PWAlterada {
            get {
                return ResourceManager.GetString("PWAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe atual.
        /// </summary>
        public static string PWATual {
            get {
                return ResourceManager.GetString("PWATual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirme a sua password.
        /// </summary>
        public static string PWCONFirm {
            get {
                return ResourceManager.GetString("PWCONFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Total.
        /// </summary>
        public static string QuantidadeTotal {
            get {
                return ResourceManager.GetString("QuantidadeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem Somos.
        /// </summary>
        public static string QuemSomos {
            get {
                return ResourceManager.GetString("QuemSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Duil é uma agência que atua como escritório de exportação para um grupo de fábricas portuguesas..
        /// </summary>
        public static string QuemSomosTexto {
            get {
                return ResourceManager.GetString("QuemSomosTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinir Palavra-passe.
        /// </summary>
        public static string REdPW {
            get {
                return ResourceManager.GetString("REdPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua palavra-passe foi redefinida com sucesso..
        /// </summary>
        public static string RedSuc {
            get {
                return ResourceManager.GetString("RedSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enviar.
        /// </summary>
        public static string Reenviar {
            get {
                return ResourceManager.GetString("Reenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enviar confirmação de email.
        /// </summary>
        public static string ReEvniarEmailLoginPage {
            get {
                return ResourceManager.GetString("ReEvniarEmailLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string referenciaPEca {
            get {
                return ResourceManager.GetString("referenciaPEca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar como novo utilizador.
        /// </summary>
        public static string Registarcomonovoutilizador {
            get {
                return ResourceManager.GetString("Registarcomonovoutilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar-se.
        /// </summary>
        public static string RegistarSE {
            get {
                return ResourceManager.GetString("RegistarSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enviar email de confirmação.
        /// </summary>
        public static string RenviarEmail {
            get {
                return ResourceManager.GetString("RenviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinir Palavra-Passe.
        /// </summary>
        public static string RePW {
            get {
                return ResourceManager.GetString("RePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        public static string Resgistar {
            get {
                return ResourceManager.GetString("Resgistar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos.
        /// </summary>
        public static string segundos {
            get {
                return ResourceManager.GetString("segundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-- Selecione um país --&gt;.
        /// </summary>
        public static string SelecionarPais {
            get {
                return ResourceManager.GetString("SelecionarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um cliente da lista.
        /// </summary>
        public static string selecioneClientedaLista {
            get {
                return ResourceManager.GetString("selecioneClientedaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-- Selecione estado --&gt;.
        /// </summary>
        public static string SelecioneEstado {
            get {
                return ResourceManager.GetString("SelecioneEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione uma fábrica da lista.
        /// </summary>
        public static string selecioneFabricadaLista {
            get {
                return ResourceManager.GetString("selecioneFabricadaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos uma peça.
        /// </summary>
        public static string SelecioneUmaPEcaPEloMenos {
            get {
                return ResourceManager.GetString("SelecioneUmaPEcaPEloMenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionado.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem informação.
        /// </summary>
        public static string semInfo {
            get {
                return ResourceManager.GetString("semInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Será redirecionado para a página de login em.
        /// </summary>
        public static string SeraRedirec {
            get {
                return ResourceManager.GetString("SeraRedirec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim, terminar sessão.
        /// </summary>
        public static string SimLogOut {
            get {
                return ResourceManager.GetString("SimLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre o Site.
        /// </summary>
        public static string SobreoSite {
            get {
                return ResourceManager.GetString("SobreoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com qualidade, proximidade e inovação..
        /// </summary>
        public static string SubtituloFraseImpacto {
            get {
                return ResourceManager.GetString("SubtituloFraseImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suécia.
        /// </summary>
        public static string Suecia {
            get {
                return ResourceManager.GetString("Suecia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemóvel.
        /// </summary>
        public static string Telemovel {
            get {
                return ResourceManager.GetString("Telemovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telémovel introduzido não corresponde com o País guardado..
        /// </summary>
        public static string telemovelnao {
            get {
                return ResourceManager.GetString("telemovelnao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja apagar.
        /// </summary>
        public static string TemACertezaQueDesejaApagar {
            get {
                return ResourceManager.GetString("TemACertezaQueDesejaApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja apagar esta encomenda?.
        /// </summary>
        public static string TemACertezaQueDesejaApagarEncomenda {
            get {
                return ResourceManager.GetString("TemACertezaQueDesejaApagarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar Sessão.
        /// </summary>
        public static string TerminarSessao {
            get {
                return ResourceManager.GetString("TerminarSessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Encomendas.
        /// </summary>
        public static string TotalEncomendas {
            get {
                return ResourceManager.GetString("TotalEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Peças Encomendadas.
        /// </summary>
        public static string TotalEnee {
            get {
                return ResourceManager.GetString("TotalEnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora.
        /// </summary>
        public static string Transportadora {
            get {
                return ResourceManager.GetString("Transportadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar Password.
        /// </summary>
        public static string upPW {
            get {
                return ResourceManager.GetString("upPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string Utilizadores {
            get {
                return ResourceManager.GetString("Utilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string UtilizadorRole {
            get {
                return ResourceManager.GetString("UtilizadorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique o seu email para restaurar a sua password..
        /// </summary>
        public static string VerifiqeuEmailPW {
            get {
                return ResourceManager.GetString("VerifiqeuEmailPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string voltarTexto {
            get {
                return ResourceManager.GetString("voltarTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seus Dados Pessoais.
        /// </summary>
        public static string youDP {
            get {
                return ResourceManager.GetString("youDP", resourceCulture);
            }
        }
    }
}
