//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duil_App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duil_App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Fábrica.
        /// </summary>
        public static string adicionarFabrica {
            get {
                return ResourceManager.GetString("adicionarFabrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Fábrica.
        /// </summary>
        public static string adicionarFabricaViewTitle {
            get {
                return ResourceManager.GetString("adicionarFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPeca {
            get {
                return ResourceManager.GetString("AdicionarPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPecaemEncomendas {
            get {
                return ResourceManager.GetString("AdicionarPecaemEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Peça.
        /// </summary>
        public static string AdicionarPecaVT {
            get {
                return ResourceManager.GetString("AdicionarPecaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar restantes peças do Cliente.
        /// </summary>
        public static string AdicionarrestantespeçasdoCliente {
            get {
                return ResourceManager.GetString("AdicionarrestantespeçasdoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar cliente.
        /// </summary>
        public static string AdidionarCliente {
            get {
                return ResourceManager.GetString("AdidionarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar dados de Utilizador.
        /// </summary>
        public static string AlterarInfodeUtilizador {
            get {
                return ResourceManager.GetString("AlterarInfodeUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nossa história.
        /// </summary>
        public static string ANossaHistoria {
            get {
                return ResourceManager.GetString("ANossaHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Duil começou em 1972. Nasceu com o sonho de promover produtos e competências portuguesas no estrangeiro, com foco nos mercados escandinavos, mantendo a porta aberta para o resto do mundo..
        /// </summary>
        public static string ANossaHistoriaTexto {
            get {
                return ResourceManager.GetString("ANossaHistoriaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nossa missão.
        /// </summary>
        public static string ANossaMissao {
            get {
                return ResourceManager.GetString("ANossaMissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar ligações duradouras entre as nossas fábricas e os mercados internacionais..
        /// </summary>
        public static string ANossaMissaoTexto {
            get {
                return ResourceManager.GetString("ANossaMissaoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Fábrica.
        /// </summary>
        public static string ApagarFabricaViewTitle {
            get {
                return ResourceManager.GetString("ApagarFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Peça.
        /// </summary>
        public static string apagarPecasVT {
            get {
                return ResourceManager.GetString("apagarPecasVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo à plataforma da Duil!.
        /// </summary>
        public static string BemVindoADuil {
            get {
                return ResourceManager.GetString("BemVindoADuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar empresa cliente.
        /// </summary>
        public static string ClienteCreateTitle {
            get {
                return ResourceManager.GetString("ClienteCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Empresa Cliente.
        /// </summary>
        public static string ClienteCreateViewTitle {
            get {
                return ResourceManager.GetString("ClienteCreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente é obrigatório.
        /// </summary>
        public static string clienteeobrigatorio {
            get {
                return ResourceManager.GetString("clienteeobrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Cliente.
        /// </summary>
        public static string ClienteNome {
            get {
                return ResourceManager.GetString("ClienteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string ClienteRole {
            get {
                return ResourceManager.GetString("ClienteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string CodPostal {
            get {
                return ResourceManager.GetString("CodPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Criar {
            get {
                return ResourceManager.GetString("Criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar encomenda.
        /// </summary>
        public static string CriarEncomenda {
            get {
                return ResourceManager.GetString("CriarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        public static string Designacao {
            get {
                return ResourceManager.GetString("Designacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Fábrica.
        /// </summary>
        public static string DetalhesdaFabricaViewTitle {
            get {
                return ResourceManager.GetString("DetalhesdaFabricaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de.
        /// </summary>
        public static string DetalhesDe {
            get {
                return ResourceManager.GetString("DetalhesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de.
        /// </summary>
        public static string detalhesDeAlgo {
            get {
                return ResourceManager.GetString("detalhesDeAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Utilizador.
        /// </summary>
        public static string DetalhesdoUtilizador {
            get {
                return ResourceManager.GetString("DetalhesdoUtilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Encomenda.
        /// </summary>
        public static string detalhesEncomendaViewTitle {
            get {
                return ResourceManager.GetString("detalhesEncomendaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da peça ref: .
        /// </summary>
        public static string DetalhesPeca {
            get {
                return ResourceManager.GetString("DetalhesPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhesTexto {
            get {
                return ResourceManager.GetString("detalhesTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * é de preenchimento obrigatório.
        /// </summary>
        public static string eDePreenchimentoObrigatorio {
            get {
                return ResourceManager.GetString("eDePreenchimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Transportadora.
        /// </summary>
        public static string EmpresaTrans {
            get {
                return ResourceManager.GetString("EmpresaTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomendas.
        /// </summary>
        public static string Encomendas {
            get {
                return ResourceManager.GetString("Encomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomenda.
        /// </summary>
        public static string EncomendaTexto {
            get {
                return ResourceManager.GetString("EncomendaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string EstadoCancelada {
            get {
                return ResourceManager.GetString("EstadoCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concretizada.
        /// </summary>
        public static string EstadoConcretizada {
            get {
                return ResourceManager.GetString("EstadoConcretizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmada.
        /// </summary>
        public static string EstadoConfirmada {
            get {
                return ResourceManager.GetString("EstadoConfirmada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado de .
        /// </summary>
        public static string EstadoDe {
            get {
                return ResourceManager.GetString("EstadoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string EstadoPendente {
            get {
                return ResourceManager.GetString("EstadoPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to este.
        /// </summary>
        public static string esteHelper {
            get {
                return ResourceManager.GetString("esteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábrica .
        /// </summary>
        public static string Fabrica {
            get {
                return ResourceManager.GetString("Fabrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fábrica é obrigatória.
        /// </summary>
        public static string fabricaeobrigatoria {
            get {
                return ResourceManager.GetString("fabricaeobrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da fábrica.
        /// </summary>
        public static string FabricaNome {
            get {
                return ResourceManager.GetString("FabricaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábricas.
        /// </summary>
        public static string Fabricas {
            get {
                return ResourceManager.GetString("Fabricas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatos permitidos: .jpg, .jpeg, .png, .gif, .webp.
        /// </summary>
        public static string FormatosImagemPermitidos {
            get {
                return ResourceManager.GetString("FormatosImagemPermitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levamos o melhor de Portugal ao mundo..
        /// </summary>
        public static string FraseDeImpacto {
            get {
                return ResourceManager.GetString("FraseDeImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        public static string FuncionarioRole {
            get {
                return ResourceManager.GetString("FuncionarioRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Alterações.
        /// </summary>
        public static string GuardarAlteracoes {
            get {
                return ResourceManager.GetString("GuardarAlteracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem atual.
        /// </summary>
        public static string ImagemAtual {
            get {
                return ResourceManager.GetString("ImagemAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem da Peça.
        /// </summary>
        public static string ImagemdoclientePeca {
            get {
                return ResourceManager.GetString("ImagemdoclientePeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem padrão.
        /// </summary>
        public static string ImagempadraoPeca {
            get {
                return ResourceManager.GetString("ImagempadraoPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string ImagemPeca {
            get {
                return ResourceManager.GetString("ImagemPeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas Clientes.
        /// </summary>
        public static string IndexClientes {
            get {
                return ResourceManager.GetString("IndexClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sessão.
        /// </summary>
        public static string IniciarSessao {
            get {
                return ResourceManager.GetString("IniciarSessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Encomenda.
        /// </summary>
        public static string modificarEncomendaViewTitle {
            get {
                return ResourceManager.GetString("modificarEncomendaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Fábrica.
        /// </summary>
        public static string ModificarFábricaVT {
            get {
                return ResourceManager.GetString("ModificarFábricaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Peça.
        /// </summary>
        public static string ModificarPecaVT {
            get {
                return ResourceManager.GetString("ModificarPecaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string modificarTexto {
            get {
                return ResourceManager.GetString("modificarTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Morada {
            get {
                return ResourceManager.GetString("Morada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada de carga.
        /// </summary>
        public static string MoradaCarga {
            get {
                return ResourceManager.GetString("MoradaCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada de descarga.
        /// </summary>
        public static string MoradaDescarga {
            get {
                return ResourceManager.GetString("MoradaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string NavClientes {
            get {
                return ResourceManager.GetString("NavClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Encomenda.
        /// </summary>
        public static string NavCriarEncomenda {
            get {
                return ResourceManager.GetString("NavCriarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encomendas.
        /// </summary>
        public static string NavEncomendas {
            get {
                return ResourceManager.GetString("NavEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fábricas.
        /// </summary>
        public static string NavFabricas {
            get {
                return ResourceManager.GetString("NavFabricas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peças.
        /// </summary>
        public static string NavPecas {
            get {
                return ResourceManager.GetString("NavPecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo de Encomendas.
        /// </summary>
        public static string NavRegistoEncomendas {
            get {
                return ResourceManager.GetString("NavRegistoEncomendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string NavUtilizadores {
            get {
                return ResourceManager.GetString("NavUtilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente.
        /// </summary>
        public static string NomeCliente {
            get {
                return ResourceManager.GetString("NomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente.
        /// </summary>
        public static string NomeDoCliente {
            get {
                return ResourceManager.GetString("NomeDoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova encomenda.
        /// </summary>
        public static string NovaEncomenda {
            get {
                return ResourceManager.GetString("NovaEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é de preenchimento obrigatório.
        /// </summary>
        public static string obrigatorio {
            get {
                return ResourceManager.GetString("obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá .
        /// </summary>
        public static string Ola {
            get {
                return ResourceManager.GetString("Ola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O que fazemos.
        /// </summary>
        public static string OQueFazemos {
            get {
                return ResourceManager.GetString("OQueFazemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promovemos produtos, apoiamos o desenvolvimento de novas ideias e acompanhamos todo o processo até ao envio..
        /// </summary>
        public static string OQueFazemosTexto {
            get {
                return ResourceManager.GetString("OQueFazemosTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de encomenda.
        /// </summary>
        public static string OrdemDeEncomenda {
            get {
                return ResourceManager.GetString("OrdemDeEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Inicial.
        /// </summary>
        public static string PaginaInicialViewTitle {
            get {
                return ResourceManager.GetString("PaginaInicialViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça.
        /// </summary>
        public static string Peca {
            get {
                return ResourceManager.GetString("Peca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peças.
        /// </summary>
        public static string Pecas {
            get {
                return ResourceManager.GetString("Pecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um cliente para ver as peças.
        /// </summary>
        public static string PorfavorAdicioneClienteParaPecas {
            get {
                return ResourceManager.GetString("PorfavorAdicioneClienteParaPecas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço total (€).
        /// </summary>
        public static string PrecoTotal {
            get {
                return ResourceManager.GetString("PrecoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço unitário.
        /// </summary>
        public static string PrecoUnit {
            get {
                return ResourceManager.GetString("PrecoUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Total.
        /// </summary>
        public static string QuantidadeTotal {
            get {
                return ResourceManager.GetString("QuantidadeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem Somos.
        /// </summary>
        public static string QuemSomos {
            get {
                return ResourceManager.GetString("QuemSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Duil é uma agência que atua como escritório de exportação para um grupo de fábricas portuguesas..
        /// </summary>
        public static string QuemSomosTexto {
            get {
                return ResourceManager.GetString("QuemSomosTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string referenciaPEca {
            get {
                return ResourceManager.GetString("referenciaPEca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        public static string Resgistar {
            get {
                return ResourceManager.GetString("Resgistar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-- Selecione um país --&gt;.
        /// </summary>
        public static string SelecionarPais {
            get {
                return ResourceManager.GetString("SelecionarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um cliente da lista.
        /// </summary>
        public static string selecioneClientedaLista {
            get {
                return ResourceManager.GetString("selecioneClientedaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-- Selecione estado --&gt;.
        /// </summary>
        public static string SelecioneEstado {
            get {
                return ResourceManager.GetString("SelecioneEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione uma fábrica da lista.
        /// </summary>
        public static string selecioneFabricadaLista {
            get {
                return ResourceManager.GetString("selecioneFabricadaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos uma peça.
        /// </summary>
        public static string SelecioneUmaPEcaPEloMenos {
            get {
                return ResourceManager.GetString("SelecioneUmaPEcaPEloMenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionado.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem informação.
        /// </summary>
        public static string semInfo {
            get {
                return ResourceManager.GetString("semInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre o Site.
        /// </summary>
        public static string SobreoSite {
            get {
                return ResourceManager.GetString("SobreoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com qualidade, proximidade e inovação..
        /// </summary>
        public static string SubtituloFraseImpacto {
            get {
                return ResourceManager.GetString("SubtituloFraseImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemóvel.
        /// </summary>
        public static string Telemovel {
            get {
                return ResourceManager.GetString("Telemovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja apagar.
        /// </summary>
        public static string TemACertezaQueDesejaApagar {
            get {
                return ResourceManager.GetString("TemACertezaQueDesejaApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que deseja apagar esta encomenda?.
        /// </summary>
        public static string TemACertezaQueDesejaApagarEncomenda {
            get {
                return ResourceManager.GetString("TemACertezaQueDesejaApagarEncomenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar Sessão.
        /// </summary>
        public static string TerminarSessao {
            get {
                return ResourceManager.GetString("TerminarSessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora.
        /// </summary>
        public static string Transportadora {
            get {
                return ResourceManager.GetString("Transportadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string Utilizadores {
            get {
                return ResourceManager.GetString("Utilizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string UtilizadorRole {
            get {
                return ResourceManager.GetString("UtilizadorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string voltarTexto {
            get {
                return ResourceManager.GetString("voltarTexto", resourceCulture);
            }
        }
    }
}
